const path = require('path');
require('dotenv').config({ path: path.join(__dirname, '..', '.env') });
const { createClient } = require('@supabase/supabase-js');

const supabase = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_SERVICE_KEY);

const RAINBOW_ORDERS = [
  { shopify_order_id: '8508565225772', email: 'dcs_domestics@yahoo.com.au', owner_name: 'Debbie Grigg', pet_name: 'Lotte', pet_type: 'Dog', called_you: 'Mom', personality: 'Loving,gentle soul', favorite_memory: 'Everyday she made me smile, I was never alone', message_to_pet: "I'm sorry for making you wait them extra days" },
  { shopify_order_id: '8508608217388', email: 'india_fields20@yahoo.com', owner_name: 'India Fields', pet_name: 'Kiptyn', pet_type: 'Cat', called_you: 'Mom', personality: 'Very sweet, cuddly, had a very good palate for food, curious', favorite_memory: 'Every time I sat on the couch, he would jump up on my shoulder and rub his head against my hair, want to smell my breath (if I was eating something), and would lick my forehead.', message_to_pet: 'Just how much he was loved and that I miss him daily. I wish I could hold him one more time.' },
  { shopify_order_id: '8508610674988', email: 'DYoYoda@aol.com', owner_name: 'Deborah McLaughlin', pet_name: 'Honey', pet_type: 'Dog', called_you: 'Mama', personality: "Happy, playful, quiet, loved her 'wubby', liked to lick my feet lol,", favorite_memory: 'She would follow me everywhere, loved to sleep with me curled up in the crook of my knees. She would walk a while then happily go in her doggie bag to go in shops with me. She actually called me mum not mama.', message_to_pet: 'I loved you so much and just wish you were here now, life is so hard without you. My tears still flow when I think of you.' },
  { shopify_order_id: '8508651995436', email: 'rosemunroe51@gmail.com', owner_name: 'rosemary munroe', pet_name: 'Snoopy', pet_type: 'Dog', called_you: 'Mama', personality: 'Loving sweet precious', favorite_memory: "Hiding in plain sight when it's time for meds", message_to_pet: 'I miss you every day and you left too fast. Love you till we meet again' },
  { shopify_order_id: '8509174546732', email: 'Itsaweenerfullife@gmail.com', owner_name: 'Corey Beerup', pet_name: 'Greta', pet_type: 'Dog', called_you: 'Mama', personality: 'Always by my side', favorite_memory: 'Just walking through the door every day, to the happiest little being, that there ever was.', message_to_pet: 'I miss you so much, but you already know that. Thank you for sending Leo to me, I needed him very much. Thank you for your unconditional love, you were the best puppy that anyone could have, I was so blessed to have you.' },
  { shopify_order_id: '8509194305836', email: 'debraskarratts70@outlook.com', owner_name: 'Debra Melling', pet_name: 'Poppy', pet_type: 'Dog', called_you: 'Mom', personality: 'Loving snuggly loyal', favorite_memory: 'Every morning she would tap me on the back of my head with her paw to wake me i would turn round to face her she would lie on her back for tickles and she would put her face next to mine for kisses', message_to_pet: 'I miss you so much my heart is aching' },
  { shopify_order_id: '8509361357100', email: 'lynnwisely@gmail.com', owner_name: 'Lynn Wisely', pet_name: 'Tico', pet_type: 'Cat', called_you: 'Mom', personality: 'Very happy cat .', favorite_memory: 'Give me big hugs everyday. Sitting on lap all the time .love getting his photos taken.', message_to_pet: "Only wish could turn back clocked last year's. Last November. The day said goodbye all 20 year's old. Missed you big time Tico." },
  { shopify_order_id: '8510040736044', email: 'tayron@heyawellness.com', owner_name: 'Tayron Brown', pet_name: 'Ellie Mae', pet_type: 'Dog', called_you: 'Mom', personality: 'Playful, demanding when she wanted something, elegant, go with the flow, old sole type of vibe', favorite_memory: 'She would go with me everywhere, we would go to festivals together where she would wear sunglasses and get her picture taken thousands of times!', message_to_pet: 'I miss you more than I could have ever known. I want her to know I love her beyond what I thought I could ever love a pet! She is my soulmate pet forever!' },
  { shopify_order_id: '8510077534508', email: 'cindy_mackenzie@hotmail.com', owner_name: 'Cindy Mackenzie', pet_name: 'Becky', pet_type: 'Dog', called_you: 'Mom', personality: 'Calm, loving, excited for food, always watching my every move and always so happy to see me', favorite_memory: 'So many amazing memories. Times at the beach and cottages, hikes in the woods, weekend drives and spending time at home with treats', message_to_pet: 'My heart hurts so bad since we said goodbye to you. You were the best decision I ever made. I will love you forever baby girl' },
  { shopify_order_id: '8510081564972', email: 'esweeney22@comcast.net', owner_name: 'Ellen Sweeney', pet_name: 'Milo', pet_type: 'Dog', called_you: 'Mom', personality: 'Sweet, attentive, and old soul', favorite_memory: 'Every time we went on day trips together. He was always my ride or die pup. I never felt alone when he was with me.', message_to_pet: 'I miss you so much my sweet brown bear. A piece of my heart left with you and ai struggle every day without you.' },
  { shopify_order_id: '8510141006124', email: 'ytweetyy1@aol.com', owner_name: 'Sandra Lewand sherman', pet_name: 'Zephyr', pet_type: 'Dog', called_you: 'Mom', personality: 'Kisses,laying close to me.AT NIGHT I WOULD GET INTO THE BED,AND HE WOULDNT LAY DOWN UNTIL I WAS SETTLED.', favorite_memory: 'JUST ALL HIS LOVE,WAS ALWAYS NEAR ME.WATCHED ME ALL THE TIME.', message_to_pet: 'I wish you could of lived forever.I still call you everyday and miss you.' },
  { shopify_order_id: '8510223647020', email: 'tabby_240@yahoo.com', owner_name: 'Tabatha Kizzier', pet_name: 'Oakley', pet_type: 'Dog', called_you: 'Mom', personality: 'Sweet, gentle, soulful', favorite_memory: 'Without fail every day he sat with me while I got ready and watched me with his loving eyes', message_to_pet: "I'm sorry I couldn't fix you" },
  { shopify_order_id: '8510502535468', email: 'andystallings@gmail.com', owner_name: 'Andy Stallings', pet_name: 'Todd Jenkins', pet_type: 'Dog', called_you: 'Dad', personality: 'Happy, playful, cuddly, obedient, nervous', favorite_memory: 'Staying up late together or sleeping together in bed when James was out of town, waiting until James went to bed to be playful or come cuddle', message_to_pet: "I miss you everyday. I'm sorry that I didn't save you. You were my best friend. You were so beautiful." },
  { shopify_order_id: '8510521016620', email: 'jenniferquail@live.com', owner_name: 'Jennifer Monaghan', pet_name: 'Grimm Boogey', pet_type: 'Dog', called_you: 'Mom', personality: 'Protective, loving', favorite_memory: 'Our car travels', message_to_pet: 'I still cry over losing you.  You are the love of my life and my soulmate' },
  { shopify_order_id: '8510610374956', email: 'g18emb1@gmail.com', owner_name: 'Gemma Bailey', pet_name: 'Izzy', pet_type: 'Dog', called_you: 'Mom', personality: 'Stubborn, sassy, sweet, loyal, mended a broken heart', favorite_memory: 'Face kisses', message_to_pet: 'I miss you every day. Im sorry' },
  { shopify_order_id: '8510837096748', email: 'myvoyou@gmail.com', owner_name: 'Catherine Miller', pet_name: 'Jack', pet_type: 'Dog', called_you: 'Mom', personality: 'Happy , sociable gentle loving to everyone who knew Jack', favorite_memory: 'Every morning he would look at me with those beautiful brown eyes I would always say good morning my boy and kiss him .after he ate Jack would come over to me for a treat . Then we would either go for a walk or a ride . I couldn\'t get out of the house without him . He would ride in the car and come to the front and put his sweet face against mine .', message_to_pet: 'I am so sorry I was the one who had to make the decision to put him down and every single day I feel guilty, \nI wish I could have done more to save you . I miss you every day and I look for you . I can\'t bring myself to adopt another dog as I am feeling like a betrayal of your life. I wish you would come to me and let me hold you one more time and kiss your beautiful face. I love you Jack with all my heart and soul.' },
  { shopify_order_id: '8510853677356', email: 'CheriseLCutbush@outlook.com', owner_name: 'Cherise Cutbush', pet_name: 'Honey', pet_type: 'Dog', called_you: 'Mom', personality: 'Playful, cuddly, always happy when she saw me, missed me when i wasn\'t there, very affectionate, beautiful natured, a foodie.', favorite_memory: 'When i used to sit and watch tv with her and cuddles, also playing fetch in the past she used to do a cute little hop when I was about to through it and do zoomies. Helped me with my seizures too alot.', message_to_pet: 'I miss you Honey every single day, you was my world and I love you very very much, my heart will never heal i hurt too much everytime i think of you. Just know what i did for you was out of pure love for you miss you forever' },
  { shopify_order_id: '8511102484780', email: 'bettyboop13742@comcast.net', owner_name: 'LORI SAMBORSKI', pet_name: 'Jake', pet_type: 'Dog', called_you: 'Mom', personality: 'Playful, great big brother to all the other pets. Loved to run and jump. Love to cuddle.Best friend', favorite_memory: "Jake was more human than dog.   He always jump up on my lap and give me hugs and kisses.  Always love to see friends come over.   Very social with whoever came into the yard. Jake couldn't wait for Christmas morning to open up his gifts.", message_to_pet: 'We miss you more than you can imagine.   Our first Christmas without you was the hardest. Love you more than you can imagine. Miss you. I love you.' },
  { shopify_order_id: '8511299027244', email: 'wagnerjaimey@gmail.com', owner_name: 'Jaimey Wagner', pet_name: 'Maddi', pet_type: 'Dog', called_you: 'Mom', personality: 'Adventurous, soulfully loving, independent, sassy, playful, compassionate, patient and just the best', favorite_memory: "Every day I'd come home n she'd be so excited to see me but my gram \"trained\" her to \"watch her tail\" because she'd smack things off the tables n such so she took it literally and would curl herself up so her tail would only hit her n I'd get home n she'd be soo excited to see me but would watch her tail and she'd just smack herself in the face with her own tail n she'd close her eyes so her tail wouldn't smack her eyes", message_to_pet: "I miss you every moment of every day. I'm so grateful for all the beautiful memories together and even though I know you're not hurting anymore and I can get out into the woods more easily without lugging your wagon and carrying you in n out I would give absolutely ANYTHING to take you on another road dog adventure. You were the best thing to have ever happened to me I'm so sooo thankful you chose me. I love you so very much Maddi puppy buttt" },
  { shopify_order_id: '8511402901804', email: 'lcshull@comcast.net', owner_name: 'Lisa Shull', pet_name: 'Rayden', pet_type: 'Dog', called_you: 'Mom', personality: 'Playful, funny stubborn smart loving loved being loved she', favorite_memory: 'Would always kiss my boo boos loved kissing me always waiting for me to come home.', message_to_pet: 'I miss you every day sweet angel always!!Are hearts are broken even now.what did you pass from?please let us know you are happy and safe. We love you always and forever our beautiful queen!!' },
  { shopify_order_id: '8511404802348', email: 'valerie@gugala.org', owner_name: 'Valerie Gugala', pet_name: 'Dexter', pet_type: 'Cat', called_you: 'Mom', personality: 'loving with family, not friendly with outsiders', favorite_memory: 'the closeness we shared', message_to_pet: 'I miss you' },
  { shopify_order_id: '8511626379564', email: 'hotrindad@aol.com', owner_name: 'Sarah Ho', pet_name: 'Archie', pet_type: 'Dog', called_you: 'Mom', personality: 'Not loving dog but always barked when me partner spoke.He always wanted attention.', favorite_memory: 'Slept on the bed very spoilt, given loads of love.', message_to_pet: 'Miss you everyday and kiss your photo and talk to you.' },
  { shopify_order_id: '8511832752428', email: 'ashleighrhancock@aol.com', owner_name: 'Ashleigh Hancock', pet_name: 'Rusty', pet_type: 'Dog', called_you: 'Mom', personality: 'Cuddly, anxious, kind', favorite_memory: 'When I was pregnant with my first child and he would go back and forth between listening to my heart and my baby.', message_to_pet: "I'm so sorry we had to let you go. I hope you were ready.  I hope I didn't wait too long or decide to soon." },
  { shopify_order_id: '8511846318380', email: 'perezbrosset@yahoo.com', owner_name: 'Antoinette Brosset', pet_name: 'Quakey', pet_type: 'Dog', called_you: 'Mom', personality: 'playful, fun, intelligent, stubborn, focused, sensitive, loving', favorite_memory: 'Quakey would put his head on my knees and look up at me in the most loving way.', message_to_pet: 'I still take our walks and I feel your presence. I am eternally grateful that you taught me to love myself. I miss you and love you and talk to you every day. You were and are my everything. I have never loved any being the way I love you.' },
  { shopify_order_id: '8511850152236', email: 'sheryl.stevenson57@gmail.com', owner_name: 'Sheryl Stevenson', pet_name: 'Lexi Lee', pet_type: 'Dog', called_you: 'Mom', personality: 'Playful, energetic, cuddler, pure love, water lover', favorite_memory: 'She loved to cuddle up under my chin with her head and give kisses. When she was a pup, she use to sleep under my chin.', message_to_pet: 'I miss you so much and you left too soon at only 6 yrs old.' },
  { shopify_order_id: '8512169836844', email: 'corinne.cos@gmail.com', owner_name: 'Corinne Costello', pet_name: 'Lexis', pet_type: 'Cat', called_you: 'Mom', personality: 'Cuddly, calm', favorite_memory: 'If I was laying down and lifted the blanket she would crawl under and lay with me.', message_to_pet: 'Sweet girl. I feel I failed you in your later years. I\'m sorry it took so long to find out you were sick and your last moments were not in my arms. You were one of the most perfect cats. It hurts to think of you because I hold so much guilt but know I love and miss you more than words can say.' },
  { shopify_order_id: '8512174162220', email: 'corinne.cos@gmail.com', owner_name: 'Corinne Costello', pet_name: 'Dollar', pet_type: 'Dog', called_you: 'Mom', personality: 'Quiet, calm, silly', favorite_memory: "All of them. Especially when dad was away for work and I'd sneak you on the bed.", message_to_pet: "You were my best bud. The most amazing dog in so many ways. You were such a sweet boy and loved everyone. I did everything I could to keep you with me but I couldn't watch you suffer. I hope you know I was there with you until the very end, and longer. Losing you changed me and I miss you every day. I love you so much my boy." },
  { shopify_order_id: '8512311951660', email: 'torgersenlori6@gmail.com', owner_name: 'Lori Torgersen', pet_name: 'Cooper', pet_type: 'Dog', called_you: 'Mom', personality: 'Loved , smart , Happy, intelligent, caring', favorite_memory: 'Our Road Trips, sitting together', message_to_pet: "I'm sorry , I miss you , my best buddy, I love you" },
];

const SOUL_ORDERS = [
  { shopify_order_id: '8508530884908', email: 'hannahnicol@hotmail.com', owner_name: 'Hannah Nicol', pet_name: 'Chester', pet_calls_you: 'Mom', photo_url: 'https://cdn.shopify.com/s/files/1/0755/4249/5532/uploads/ad25d80d11aa9ef72f43a2a4ba9f6f64.jpeg', species: 'Dog', life_stage: 'Adult', personality: 'Playful, loving, and sometimes cautious,', question: 'Are they happy' },
  { shopify_order_id: '8508727099692', email: 'knboyce03@gmail.com', owner_name: 'Krista Boyce', pet_name: 'Nova', pet_calls_you: 'Mom', photo_url: 'https://cdn.shopify.com/s/files/1/0755/4249/5532/uploads/4a73ff400185ee484cc4cd01bc24ccf0.jpeg', species: 'Dog', life_stage: 'Adult', personality: 'Sweet, gentle, loving, the best girl', question: 'Does she want us to do everything we can when we receive the outcome? Is she doing ok?' },
  { shopify_order_id: '8508791783724', email: 'dcequihua85@att.net', owner_name: 'Danielle Equihua', pet_name: 'Rosa', pet_calls_you: 'Mom', photo_url: 'https://cdn.shopify.com/s/files/1/0755/4249/5532/uploads/67c5f2f7fb1682718359d580b6494d47.jpeg', species: 'Dog', life_stage: 'Senior', personality: 'Stubborn, talkative, affectionate, intelligent, relaxed', question: 'Is she happy that I rescued her, and the life she has now then before we met?' },
  { shopify_order_id: '8508947235116', email: 'david.p.sharpe@gmail.com', owner_name: 'David Sharpe', pet_name: 'Liberace', pet_calls_you: 'Dad', photo_url: 'https://cdn.shopify.com/s/files/1/0755/4249/5532/uploads/f5bccba444a0bf17a132dd517b121bb8.jpeg', species: 'Dog', life_stage: 'Senior', personality: 'Protective, stubborn, loving, codependent, and opinionated', question: 'How is he feeling overall/is there anything I can do differently to make him more comfortable?' },
  { shopify_order_id: '8509457170732', email: 'craymk1@sbcglobal.net', owner_name: 'Carrie Little', pet_name: 'Zeus', pet_calls_you: 'Mom', photo_url: 'https://cdn.shopify.com/s/files/1/0755/4249/5532/uploads/be6cecdfe2d41124fafc4ea21a5adb4b.jpeg', species: 'Dog', life_stage: 'Senior', personality: '', question: 'Are they happy. My Zeus died 12/23/2026' },
  { shopify_order_id: '8509534109996', email: 'mandy_higgins86@yahoo.com', owner_name: 'Amanda Higgins', pet_name: 'Figaro', pet_calls_you: 'Mom', photo_url: 'https://cdn.shopify.com/s/files/1/0755/4249/5532/uploads/26e582d00b8bbc28ed1953860bbf9904.jpg', species: 'Cat', life_stage: 'Baby/Puppy/Kitten', personality: 'Stubborn and playful', question: 'Are you happy living with me?' },
  { shopify_order_id: '8509702078764', email: 'sumnercat1@gmail.com', owner_name: 'Kelty McWalter', pet_name: 'Finn', pet_calls_you: 'Mom', photo_url: 'https://cdn.shopify.com/s/files/1/0755/4249/5532/uploads/779e703ae83dd91cc6c0f3e1bee764be.jpeg', species: 'Cat', life_stage: 'Adult', personality: 'Funny, silly, cuddly, loyal. Loving, kind', question: 'Are you happy I am your mom? Do you love your family?' },
  { shopify_order_id: '8509802414380', email: 'naomikster@gmail.com', owner_name: 'naomi kalvin', pet_name: 'Pepper', pet_calls_you: 'Human', photo_url: 'https://cdn.shopify.com/s/files/1/0755/4249/5532/uploads/b4eaa82dc1d2e31d0ee7613d53b94036.jpg', species: 'Dog', life_stage: 'Adult', personality: 'Unsettled', question: 'Why is she always so anxious?' },
  { shopify_order_id: '8510174724396', email: 'marycarroll_597@yahoo.com', owner_name: 'Mary Carroll', pet_name: 'Teddy', pet_calls_you: 'Mom', photo_url: 'https://cdn.shopify.com/s/files/1/0755/4249/5532/uploads/1bda46d5abd3d65805cbee3a20b921aa.jpg', species: 'Dog', life_stage: 'Senior', personality: 'Funny silly smart goofy now as senior doggie quieter still smiles great sleeper loves to lean on me', question: 'What is 1 of your great memories with me?' },
  { shopify_order_id: '8510212473132', email: 'cdovo25@gmail.com', owner_name: 'Carolyn Dovo', pet_name: 'Lacey', pet_calls_you: 'Mom', photo_url: 'https://cdn.shopify.com/s/files/1/0755/4249/5532/uploads/8fab7dcef20c1305a60bbdf371a268ab.jpg', species: 'Dog', life_stage: 'Adult', personality: 'Playful, cuddly and loving', question: 'Is my dog happy?' },
  { shopify_order_id: '8510327521580', email: 'hirecheryljacobson@gmail.com', owner_name: 'Cheryl Jacobson', pet_name: 'Gizmo', pet_calls_you: 'Mom', photo_url: 'https://cdn.shopify.com/s/files/1/0755/4249/5532/uploads/140c109e710cfa19e0fedfc3f63e5090.jpg', species: 'Dog', life_stage: 'Adult', personality: 'Playful, loving Velcro dog', question: "Does he know that he's sick and that we're having surgery done to try to save his life so he can have more time with us? Is that what he wants?" },
  { shopify_order_id: '8510356226348', email: 'philapilr@aol.com', owner_name: 'Rachel Philapil', pet_name: 'Maverick', pet_calls_you: 'Mama', photo_url: 'https://cdn.shopify.com/s/files/1/0755/4249/5532/uploads/5a96c2163505f89d2e506a34476c20ad.jpeg', species: 'Dog', life_stage: 'Young', personality: 'Playful, energetic, loving', question: 'I lost my boyfriend and our dog within a year of each other. I  found Maverick on a rescue  site by accident ( not really).  When I went to go see him I didn\'t think I was ready for a dog. He was the last of his litter because he was very hyper.  He jumped into my arms and it just made me so happy.  I tell him everyday that I love him and that he saved me.  I want to know if he really did choose me and loves me as much as I love him.' },
  { shopify_order_id: '8510381261100', email: 'drlschairer@hotmail.com', owner_name: 'Lauren Schairer', pet_name: 'Tomatillo', pet_calls_you: 'Mom', photo_url: 'https://cdn.shopify.com/s/files/1/0755/4249/5532/uploads/3cf40ad064e782d72bf81c88272a884f.jpg', species: 'Dog', life_stage: 'Adult', personality: 'Playful, snuggly,dilly', question: 'Is he happy? Does he want me to do anything in particular that I do not do?' },
  { shopify_order_id: '8510773952812', email: 'nollerc23@yahoo.com', owner_name: 'Chelsea Noller', pet_name: 'Salem', pet_calls_you: 'Mom', photo_url: 'https://cdn.shopify.com/s/files/1/0755/4249/5532/uploads/63507c1f455adb515f699b36547ab2a7.jpeg', species: 'Cat', life_stage: 'Adult', personality: 'Sassy, cuddly, dominant, loving', question: 'Why do you pick on Charlee?' },
  { shopify_order_id: '8510952800556', email: 'trishtymecki@gmail.com', owner_name: 'Patricia V Johnson', pet_name: 'Shiva', pet_calls_you: 'Mom', photo_url: 'https://cdn.shopify.com/s/files/1/0755/4249/5532/uploads/676932d66391e5248156d0230048e09d.jpg', species: 'Dog', life_stage: 'Senior', personality: 'Cuddly, silly, loving, smart', question: 'Why did you pick me?' },
  { shopify_order_id: '8511305580844', email: 'jennifer.stoklosa@gmail.com', owner_name: 'Jennifer Stoklosa', pet_name: 'Cleo', pet_calls_you: 'Mom', photo_url: 'https://cdn.shopify.com/s/files/1/0755/4249/5532/uploads/d32d9c34f73821b0e6b9db353aaa1a2a.jpg', species: 'Dog', life_stage: 'Young', personality: 'Smart, goofy, curious', question: 'Are they happy. What are their favorite things' },
  { shopify_order_id: '8511309447468', email: 'hmpklausing@gmail.com', owner_name: 'Holly Klausing', pet_name: 'Franklyn Wilmer', pet_calls_you: 'Mom', photo_url: 'https://cdn.shopify.com/s/files/1/0755/4249/5532/uploads/78b7bd93ec4e06ddad07abaa5f4d433d.jpeg', species: 'Dog', life_stage: 'Young', personality: 'Stubborn, playful, velcro', question: 'Why is he anxious in the car?' },
  { shopify_order_id: '8511402017068', email: 'valerie@gugala.org', owner_name: 'Valerie Gugala', pet_name: 'jasmine', pet_calls_you: 'Mom', photo_url: 'https://cdn.shopify.com/s/files/1/0755/4249/5532/uploads/71194772aa7f474fb8418a042b3f48a9.jpg', species: 'Cat', life_stage: 'Senior', personality: 'friendly on her terms', question: 'what can we do to give you the best life' },
  { shopify_order_id: '8511441207596', email: 'pattijofindley@gmail.com', owner_name: 'Patti Findley', pet_name: 'Finn', pet_calls_you: 'Mama', photo_url: 'https://cdn.shopify.com/s/files/1/0755/4249/5532/uploads/15b8e282adc8d6bfeca347e637de0ae4.jpeg', species: 'Dog', life_stage: 'Young', personality: 'Playful, loving, follows me everywhere', question: "Why are there days when he doesn't eat?" },
  { shopify_order_id: '8511467979052', email: 'tiffany.l.page@gmail.com', owner_name: 'Tiffany Page', pet_name: 'Holly', pet_calls_you: 'Human', photo_url: 'https://cdn.shopify.com/s/files/1/0755/4249/5532/uploads/cf57670b92a47518625c73a1dcf00364.jpg', species: 'Dog', life_stage: 'Senior', personality: "Loves the humans she knows. Doesn't like other dogs, since she used to have to protect my other dog (they were together for about 9 years before he passed). Love exploring, sniffing, can be playful", question: 'Holly is currently going through Chemo for lymphoma. I am curious on how she is feeling about me choosing chemo instead of just doing the basic treatment and would have caused a shorter life.' },
  { shopify_order_id: '8511785173292', email: 'laurenlsparks@gmail.com', owner_name: 'Lauren Sparks', pet_name: 'Baxter', pet_calls_you: 'Mama', photo_url: 'https://cdn.shopify.com/s/files/1/0755/4249/5532/uploads/a664fd7a93ebbc4921ea4d72d60ec7ad.jpeg', species: 'Dog', life_stage: 'Adult', personality: 'Loyal, close companion, goofy', question: 'He lost his brother a few months ago. Does he want a new sibling or just depressed and will get better?' },
  { shopify_order_id: '8511812993324', email: 'meech22@yahoo.com', owner_name: 'Michelle Coronado', pet_name: 'Meow', pet_calls_you: 'Mom', photo_url: 'https://cdn.shopify.com/s/files/1/0755/4249/5532/uploads/2a0ae08d0cdabf598fe9bb55d537acc2.png', species: 'Cat', life_stage: 'Senior', personality: 'Cuddly friendly quiet', question: 'Are you okay?' },
  { shopify_order_id: '8511822463276', email: 'anna.bowling05@gmail.com', owner_name: 'Anna Bowling', pet_name: 'Boone "Boo Boo"', pet_calls_you: 'Mom', photo_url: 'https://cdn.shopify.com/s/files/1/0755/4249/5532/uploads/b230ad49bfe584f8172403e9560617b1.jpg', species: 'Dog', life_stage: 'Adult', personality: 'Loving, loves snuggles, follows me everywhere I go, likes walks and loves to sniff', question: 'Does he like being the only dog, or would he want a friend?' },
  { shopify_order_id: '8511873384748', email: 'carleymoe13090@gmail.com', owner_name: 'Carley Sullivan', pet_name: 'Capone', pet_calls_you: 'Human', photo_url: 'https://cdn.shopify.com/s/files/1/0755/4249/5532/uploads/6f59df9a775313f8306537d77638aeb3.jpeg', species: 'Dog', life_stage: 'Senior', personality: 'Loving; silly', question: 'What is your favorite memory?' },
  { shopify_order_id: '8511950782764', email: 'tinakaylester@gmail.com', owner_name: 'Tina Lester', pet_name: 'Tiki', pet_calls_you: 'Mom', photo_url: 'https://cdn.shopify.com/s/files/1/0755/4249/5532/uploads/fe630fb86db927a64979dd266866dbf9.jpeg', species: 'Dog', life_stage: 'Young', personality: 'Anxious, fearful, coming out of her shell slowly', question: 'How can I get you to let me put a harness on you so we can go on adventures outside?' },
  { shopify_order_id: '8511961366828', email: 'DAKATTAK@HOTMAIL.COM', owner_name: 'DENISE CURTIN', pet_name: 'Ranger Fireball', pet_calls_you: 'Mom', photo_url: 'https://cdn.shopify.com/s/files/1/0755/4249/5532/uploads/28598c1c30bb1c7562b656a085415ed5.jpeg', species: 'Dog', life_stage: 'Adult', personality: 'Playful, stubborn, routine oriented, sweet', question: "Why doesn't he like other dogs or other humans?" },
  { shopify_order_id: '8511963660588', email: 't1nch3rl@comcast.net', owner_name: 'Lori Tincher', pet_name: 'Furgus', pet_calls_you: 'Mom', photo_url: 'https://cdn.shopify.com/s/files/1/0755/4249/5532/uploads/64c3e8785c630289a10db7698579d1f5.jpeg', species: 'Dog', life_stage: 'Adult', personality: 'Sweet,stubborn,follows everywhere', question: 'Is he in pain?' },
  { shopify_order_id: '8511972311340', email: 'rubysandowalls@gmail.com', owner_name: 'Ruby Sandoval', pet_name: 'Chavo', pet_calls_you: 'Mom', photo_url: 'https://cdn.shopify.com/s/files/1/0755/4249/5532/uploads/edeff47f42d01c0b2c33ae3e1bb3076c.jpeg', species: 'Dog', life_stage: 'Senior', personality: '', question: '' },
  { shopify_order_id: '8512045023532', email: 'kmemmen95@gmail.com', owner_name: 'Kate Raftovich', pet_name: 'Rubble', pet_calls_you: 'Mom', photo_url: 'https://cdn.shopify.com/s/files/1/0755/4249/5532/uploads/eb9bed8f1191645f7adbdb3c137171ff.jpeg', species: 'Dog', life_stage: 'Young', personality: 'Playful, sassy, loving and cuddly', question: 'Why did you pick me' },
  { shopify_order_id: '8512105349420', email: 'brownbarbara22@gmail.com', owner_name: 'Barbara Mueller', pet_name: 'Duchess', pet_calls_you: 'Mama', photo_url: 'https://cdn.shopify.com/s/files/1/0755/4249/5532/uploads/3e8aa0a4670af6a95342f5bd7f1c4830.jpeg', species: 'Dog', life_stage: 'Adult', personality: 'Loving, protective, obedient', question: 'Why is Duchess terrified of any fire or smoke she sees on TV or outdoor grills?' },
  { shopify_order_id: '8512110002476', email: 'msspungen@aol.com', owner_name: 'Jenn Woolston', pet_name: 'Ralphie', pet_calls_you: 'Mom', photo_url: 'https://cdn.shopify.com/s/files/1/0755/4249/5532/uploads/1c1ed0262968b7008da1bcfe5ddbccf3.jpeg', species: 'Cat', life_stage: 'Young', personality: 'Cuddly, Fun, Watchful', question: 'What was his early life like and why did he choose me?' },
  { shopify_order_id: '8512155615532', email: 'jessica.madeley15@gmail.com', owner_name: 'Jessica Madeley', pet_name: 'Tera', pet_calls_you: 'Mom', photo_url: 'https://cdn.shopify.com/s/files/1/0755/4249/5532/uploads/b107796f58fcd70f41d3b388baf365d6.jpeg', species: 'Dog', life_stage: 'Senior', personality: 'Cuddly, stubborn & loving', question: 'Did I make the right decision?' },
  { shopify_order_id: '8512165282092', email: 'corinne.cos@gmail.com', owner_name: 'Corinne Costello', pet_name: 'Koda', pet_calls_you: 'Mom', photo_url: 'https://cdn.shopify.com/s/files/1/0755/4249/5532/uploads/171250c883ed584ae25d03128402d0a0.jpeg', species: 'Dog', life_stage: 'Adult', personality: 'Goofy, excited', question: 'Am I doing enough for you?' },
  { shopify_order_id: '8512338362668', email: 'moslowski@yahoo.com', owner_name: 'Meredith Oslowski', pet_name: 'Samson', pet_calls_you: 'Mom', photo_url: 'https://cdn.shopify.com/s/files/1/0755/4249/5532/uploads/1bb69c7e35e0e0fe7a407f1e32dc67a3.jpeg', species: 'Dog', life_stage: 'Adult', personality: '', question: 'Are you happy?' },
];

async function run() {
  const sendAfter = new Date(Date.now() - 60000).toISOString(); // 1 min ago = process immediately

  console.log(`Inserting ${RAINBOW_ORDERS.length} Rainbow Bridge orders...`);
  let rainbowOk = 0, rainbowSkip = 0;
  for (const order of RAINBOW_ORDERS) {
    const { data: existing } = await supabase
      .from('rainbow_orders')
      .select('id')
      .eq('shopify_order_id', order.shopify_order_id)
      .maybeSingle();

    if (existing) {
      console.log(`  SKIP rainbow ${order.shopify_order_id} (${order.pet_name}) - already exists`);
      rainbowSkip++;
      continue;
    }

    const { error } = await supabase.from('rainbow_orders').insert({
      ...order,
      status: 'pending',
      send_after: sendAfter,
    });

    if (error) {
      console.error(`  ERROR rainbow ${order.shopify_order_id}:`, error.message);
    } else {
      console.log(`  OK rainbow ${order.shopify_order_id} - ${order.pet_name} (${order.email})`);
      rainbowOk++;
    }
  }

  console.log(`\nInserting ${SOUL_ORDERS.length} Soul Reading orders...`);
  let soulOk = 0, soulSkip = 0;
  for (const order of SOUL_ORDERS) {
    const { data: existing } = await supabase
      .from('soul_reading_orders')
      .select('id')
      .eq('shopify_order_id', order.shopify_order_id)
      .maybeSingle();

    if (existing) {
      console.log(`  SKIP soul ${order.shopify_order_id} (${order.pet_name}) - already exists`);
      soulSkip++;
      continue;
    }

    const { error } = await supabase.from('soul_reading_orders').insert({
      ...order,
      status: 'pending',
      send_after: sendAfter,
    });

    if (error) {
      console.error(`  ERROR soul ${order.shopify_order_id}:`, error.message);
    } else {
      console.log(`  OK soul ${order.shopify_order_id} - ${order.pet_name} (${order.email})`);
      soulOk++;
    }
  }

  console.log(`\nDone!`);
  console.log(`Rainbow: ${rainbowOk} inserted, ${rainbowSkip} skipped`);
  console.log(`Soul:    ${soulOk} inserted, ${soulSkip} skipped`);
  console.log(`Total:   ${rainbowOk + soulOk} new orders queued for processing`);
}

run().catch(err => {
  console.error('Fatal:', err.message);
  process.exit(1);
});
